# Site settings
title: Bizacat
email: tina.bizaca@gmail.com
description: Tina Bizaca's online portfolio
baseurl: "" # the subpath of your site, e.g. /blog/
url: "/" # the base hostname & protocol for your site
github_username:  bizacat

# Build settings
markdown: kramdown
